### ISSUE TITLE
AU Base Identifier datatype profiles: standardise constraints on type and type.text (and maybe others)

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#302]
The [AU Base Practitioner Profile](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-practitioner.html) has 4 identifier slices, with discriminators `pattern:type, value:system`.

Three of the four slices have `type` and `type.text` as optional, however the slice for AHPRA identifier mandates both and I cannot figure out why that is the case. Or should they be optional as for the others?

**Comment by robeastwood-agency** [comment]
A reassessment was performed given the shift to identifier datatype profiles, with the conclusion that this query is still in play.

However, this variation is not limited to the above mentioned Practitioner related identifiers - ie apart from the list below, other Identifier datatype profiles have identifier.type and identifier.type.text as optional:
- [Commonwealth Seniors Health Card Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-cwlthseniorshealthcardnumber.html) mandates type but not type.text
- [Employee Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-employeenumber.html) mandates both
- [Health Care Card Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-healthcarecardnumber.html) mandates type but not type.text
- [Healthcare Provider Identifier – Organisation](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-hpionumber.html) mandates type.text but not type
- [Medical Record Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-medicalrecordnumber.html) mandates type but not type.text
- [Medicare Provider Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-medicareprovidernumber.html) mandates type but not type.text
- [NPIO](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-nationalprovideridentifieratorganisation.html) mandates type but not type.text
- [Pensioner Concession Card Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-pensionerconcessioncardnumber.html) mandates type but not type.text
- [Private Health Insurance Member Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-insurernumber.html) mandates type but not type.text

**Comment by dtr-agency** [comment]
My perspective is different, each identifier should be defined appropriately for its purpose. Standardisation for its sake is not useful. Where the same rule is applicable or appropriate it should be represented consistently but I disagree with attempting to make all the identifier data types have the same rules as its own end.

**Comment by robeastwood-agency** [comment]
Closing; following on from the comment above.

Each identifier profile to be taken on a case by case basis, via other tickets as required.

**Comment by dtr-agency** [comment]
This ticket is still relevant - assessment not yet made on whether the same rule, where applicable, has been applied. This is part of the bundled set being handled as structural changes.

**Comment by dtr-agency** [comment]
Copied over previous concerns from #362 
employeeNumber has a number of aspects that differ from other slices, which may be intentional, but may also be design issues :

- the name is not ideal as some identifiers may not actually be numbers (and potentially they may not identify employees); suggest "Employee identifier" as a compromise.
- PractitionerRole.identifier:employeeNumber.type.text is 1..1 whereas others are 0..1
- PractitionerRole.identifier:employeeNumber.type.text has a fixedValue of "Employee Number"; this would seem to rule out local labels such as "QLD Health employee number" etc (vs mandating coding.display value)
- PractitionerRole.identifier:employeeNumber.assigner is 1..1; would the system value carry this information
- alternatively, as assigner would have the scoping organisation entity (ABN or HPI-O) then the system value may be redundant
- PractitionerRole.identifier:employeeNumber.assigner.display is 1..1 - also not present elsewhere

**Comment by dtr-agency** [comment]
The group of issues around Identifier.type are being progressed together as a proposal for ratification at the WG. A work in progress [build of the proposal](http://build.fhir.org/ig/ci-collaborative/au-fhir-base-r4/branches/Proposal-identifier-data-type-structural-changes/profiles.html ) is available.

A set of principles on Identifier.type are driving the changes in this proposal. The current thinking is:
1. if a code is fixed it shall be from the [V2 Identifier Type - AU Extended](http://build.fhir.org/ig/hl7au/au-fhir-base/ValueSet-au-hl7v2-0203.html) value set 
1. if a code is fixed there should not be the 'required binding' present as it is already satisfied by the fixed code
1. code will be fixed by pattern
1. if no code is fixed then a required binding shall be present either to HL7 0203 or to a subset
1. every Identifier data type profile should have guidance on Identifier.type: 
    * a fixed code in structure, or
    * a preferred code in Usage Notes (only applies to ABN, ARBN, ACN)
1. text should be optional, and not fixed
