### ISSUE TITLE
AU FHIR Base identifier data type profiles - bad use of pattern, fixed value, and binding.

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#319]
From Zulip thread https://chat.fhir.org/#narrow/stream/179166-implementers/topic/CodeableConcept.20child.20elements.20appears.20twice

There are profiles where CodeableConcept elements have a pattern and their child element `text` has a fixed value, e.g. Practitioner.
This is invalid (see Zulip thread) but is not rejected by the validator. It does create a strange display in the snapshot tab.

**Comment by RichardTON** [comment]
I suggest that the solution is to move the fixed value from the text element to the pattern.
The pattern becomes
`      <patternCodeableConcept>
        <coding>
          <system value="http://terminology.hl7.org/CodeSystem/v2-0203"/>
          <code value="NPI"/>
        </coding>
        <text value="HPI-I"/>
      </patternCodeableConcept>'
and the fixed value for text is removed,

**Comment by oridashi** [comment]
need to review in PA; this is not quite the same as intent 
* if there is a type then must be a code + system as specified
* text is optional but fixed if present
- using pattern alone would require the text to be present if type is present..

**Comment by robeastwood-agency** [comment]
A reassessment of this issue was undertaken, given the recent shift for all identifiers to be represented in datatype profiles.

In short, the issue remains in the below listed Identifier datatype profiles, when the following conditions exist:
- Identifier.type has patternCodeableConcept to constrain coding AND
- Identifier.type.text (in a separate node) has a min value and fixedString constraints

The HPI-O identifier profile does not exhibit this problem as it includes the type.text constraint within the patternCodeableConcept node; like this
```
<patternCodeableConcept>
     <coding>
          <system value="http://terminology.hl7.org.au/CodeSystem/v2-0203" />
          <code value="NOI" />
     </coding>
     <text value="HPI-O" />  <!-- NOTE THIS LINE -->
</patternCodeableConcept>
```

The fix is to follow the pattern used by HPI-O Identifier profile; and it affects these Identifier datatype profiles:
- [AU AHPRA Registration Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-ahpraregistrationnumber.html)
- [AU Commonwealth Seniors Health Card Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-cwlthseniorshealthcardnumber.html)
- [AU Employee Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-employeenumber.html)
- [AU Health Care Card Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-healthcarecardnumber.html)
- [AU HPI-I Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-hpiinumber.html)
- [AU IHI Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-ihinumber.html)
- [AU Medical Record Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-medicalrecordnumber.html)
- [AU Medicare Card Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-medicarecardnumber.html)
- [AU Medicare Prescriber Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-medicareprescribernumber.html) 
- [AU Medicare Provider Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-medicareprovidernumber.html)
- [AU National Provider Identifier At Organisation](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-nationalprovideridentifieratorganisation.html)
- [AU Pensioner Concession Card Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-pensionerconcessioncardnumber.html)
- [AU Private Healthcare Insurer Number](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-insurernumber.html)

Note that the same issue may be other profiles, as the above assessment was made on Identifier datatype profiles only.

**Comment by dtr-agency** [comment]
In general type.text should not be set in AU Base profiles. It is a misuse of that element - the intention of setting a code with display is to declare a common means of representing this data, text should be allowed to serve a local purpose, e.g. for the sending system to indicate a meaningful local label. 

It is unreasonable for the national definition of an identifier data type to prohibit the inclusion of a local label for an identifier, i.e. the system will reject a medical record number if an identifier has the text URN.

Definition of text element:
`A human language representation of the concept as seen/selected/uttered by the user who entered the data and/or which represents the intended meaning of the user.
`
There will be a forthcoming issue for this to be removed to be reconsidered for real world identifiers.

**Comment by RichardTON** [comment]
au-medicareprovidernumber has a binding to a CodeSystem.
Bindings are to ValueSets, not CodeSystems.

**Comment by RichardTON** [comment]
The identifier profiles include a mandatory slice with a fixed value of identifier type, so the binding is redundant and distracting.
Examples with this problem include
- au-ahpraregistrationnumber
- au-cwlthseniorshealthcardnumber
- au-employeenumber
- au-ihinumber

**Comment by dtr-agency** [comment]
#### Overview
The issues around Identifier.type across the set of profiles (#471 | #302 | #319) are being progressed together as a proposal for ratification at the WG. A work in progress [build of the proposal](http://build.fhir.org/ig/ci-collaborative/au-fhir-base-r4/branches/Proposal-identifier-data-type-structural-changes/profiles.html ) is available.

The expectation is that Identifier profiles are not 'Base profiles'. These profiles represent well formed identifiers that may be used as-is for the purposes of conformance and are the recommended agreed representations of these identifiers.

#### Principles
A set of principles on Identifier.type are driving the changes in this proposal. The current thinking is:
1. every Identifier data type profile should have guidance on Identifier.type: 
    * a fixed code in structure, or
    * a preferred code in Usage Notes (only applies to ABN, ARBN, ACN)
1. if a code is fixed:
    1. it shall be from the required [V2 Identifier Type - AU Extended](http://build.fhir.org/ig/hl7au/au-fhir-base/ValueSet-au-hl7v2-0203.html) value set 
    1. shall not have the 'required binding' present as it is already satisfied by the fixed code
    1. code will be fixed by pattern
    1. coding will not be restricted to 1..1 in AU Base
1. if no code is fixed then a required binding shall be present either to [V2 Identifier Type - AU Extended](http://build.fhir.org/ig/hl7au/au-fhir-base/ValueSet-au-hl7v2-0203.html) value set or to a subset such as [DVA Entitlement](http://build.fhir.org/ig/hl7au/au-fhir-base/ValueSet-dva-entitlement.html)
1. text should be optional, and not fixed in all real world identifier profiles as p

**Comment by robeastwood-agency** [comment]
Further updates have been made to the build branch to align with the current proposal: http://build.fhir.org/ig/ci-collaborative/au-fhir-base-r4/branches/Proposal-identifier-data-type-structural-changes/profiles.html
