### ISSUE TITLE
Care Agency Employee Identifier - code not predefined in the mandated valueset 

### ISSUE THREAD

**Issue by vikasmittal-dh** [hl7au/au-fhir-base#444]
Care Agency Employee Identifier:

The value set for identifier.type is mandated but the code has not been predefined.
The most appropriate code is probably - EI.

Please also note that the example doesn't conform to the slice and the CAE datatype profile.

**Comment by robeastwood-agency** [comment]
Link to CAE Identifier datatype profile: [http://hl7.org.au/fhir/StructureDefinition/au-careagencyemployeeidentifier](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-careagencyemployeeidentifier.html)

Note that this is related to (and possibly subsumed) by the expanded scope of ticket #302 ('AU Base Identifier datatype profiles: standardise constraints on type and type.text (and maybe others)')

**Comment by oridashi** [comment]
need to decide here if this is a specialisation of general employee number or just a different type of identifier

**Comment by dtr-agency** [comment]
This is a different type of identifier rather than a specialisation of general employee number - an employee would have both.

An employee at a care agency will have their employee identifier issued by their employer - but to interact with the My Health Record system in this capacity they will need a specific 'Care Agency Employee Identifier' that is used when interacting with the My Health Record system.

**Comment by dtr-agency** [comment]
In progress: http://build.fhir.org/ig/ci-collaborative/au-fhir-base-r4/branches/SRAIG-177-introduce-code-for-CAE-identifier/StructureDefinition-au-careagencyemployeeidentifier.html
