### ISSUE TITLE
HealthcareService - accommodating "after hours" for Contactpoint.use 

### ISSUE THREAD

**Issue by davidmckillop** [hl7au/au-fhir-base#458]
After hours contact has been recorded by some systems and the information has been made available in systems.
Given that the data type [ContactPoint](http://hl7.org/fhir/R4/datatypes.html#ContactPoint) is normative and the value set [contact-point-use](http://hl7.org/fhir/R4/valueset-contact-point-use.html) is normative and required, there seems little scope for having details of "After hours contact" except via an extension.

Feedback has been sought on Zulip via [How to accommodate ContactPoint.use = "After hours"
](https://chat.fhir.org/#narrow/stream/179166-implementers/topic/How.20to.20accommodate.20ContactPoint.2Euse.20.3D.20.22After.20hours.22)

**Comment by davidmckillop** [comment]
@brianpos on Zulip suggested looking at the extension [contactpoint-availabletime](http://hl7.org/fhir/uv/vhdir/2018Sep/StructureDefinition-contactpoint-availabletime.html) in the  VhDir profile [vhdir-healthcareservice](http://hl7.org/fhir/uv/vhdir/2018Sep/StructureDefinition-vhdir-healthcareservice.html).
This extension would enable different contact details for the different periods of the day e.g. 8am-5pm and 5pm to 8am, and the priority of the contact could be ordered using HealthcareService.telecom.rank.

**Comment by robeastwood-agency** [comment]
It is proposed to introduce an extension on [AU Base HealthcareService](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-healthcareservice.html) to allow the recording of different phone numbers (and potentially other telecom systems) for different purposes such as after hours.

The NHSD FHIR IG has such an extension. It is proposed to extend AU Base in a substantially similar manner.
- https://build.fhir.nhsd.healthdirect.org.au/StructureDefinition-nhsd-healthcareservice.html
- https://build.fhir.nhsd.healthdirect.org.au/StructureDefinition-au-contact-purpose.html

Consideration should be given as to whether it is semantically correct to include the including the [ContactEntityType codesystem](http://hl7.org/fhir/STU3/codesystem-contactentity-type.html) in the value set for the telecom purpose:
https://build.fhir.nhsd.healthdirect.org.au/ValueSet-valueset-au-contact-purpose.html

The Contact Entity Type code system is focused on contact entities rather than telecom purposes.

Given the potential for the addition of a Healthcare Service “contact” element in R5, use of the same code system could lead to two different ways to represent the same thing.

**Comment by dtr-agency** [comment]
In Agency use cases we really need a means of indicating contact purpose and aligning them across a number of other resources e.g. Patient.contact and Organization.contact. We're also looking to support after hours contact and several other contact purpose values for PractitionerRole.

**Comment by robeastwood-agency** [comment]
This was extensively discussed at PAWG today, see [minutes](https://confluence.hl7australia.com/display/PA/2020-08-12+Minutes). 

The outcome was
- this is broader than the resource HealthcareService and more than just "after hours"; ie it is about representing different types of contact purposes within a variety of resources; eg (as described in tickets linked in above comment)
  - HealthcareService, Organization or PractitionerRole after hours or emergency contacts
  - Patient.contact next of kin or emergency
  - Organization for contact for correction of records, or contact for the retrieval of records
- agreement that this would ideally be an extension on ContactPoint to enable broad applicability
- the additional values would be in a HL7 AU CodeSystem that were similar to the [NHSD set](https://build.fhir.nhsd.healthdirect.org.au/CodeSystem-au-contact-purpose.html) which would be combined to the core set via a ValueSet
- actionm on the Agency team to work up the content for this CodeSystem

**Comment by dtr-agency** [comment]
Draft code system and value set here: https://confluence.hl7australia.com/display/PA/Contact+purpose+terminology

**Comment by dbojicic-agency** [comment]
HL7 AU Base Implementation Guide has been updated to include
- Extension [Contact Purpose](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-contact-purpose.html) on ContactPoint data type, used to represent the purpose for which a contact can be reached, e.g. after hours or billing, and related terminology resources:
- [Contact Purpose Extended](http://terminology.hl7.org.au/ValueSet/contact-purpose) ValueSet and
- [Contact Purpose](http://terminology.hl7.org.au/CodeSystem/contact-purpose) CodeSystem.

Update to the AU Base HealthcareService to make use of this new extension will be provided shortly by another PR:

AU Base HealthcareService profile will not reference the extension  directly from StructureDefinition. The extension will be included by guidance only - via a guidance statement on the use of extension on the AU Base HealthcareService page and a link to the extension page. One or more existing examples will be updated to demonstrate the use of the extension.
