### ISSUE TITLE
Consider extension on AU Base PractitionerRole for preferred name

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/au-fhir-base#465]
It is proposed to introduce an extension on [AU Base PractitionerRole](http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-practitionerrole.html) to support a preferred name.  Whilst the Practitioner resource has provision for a practitioner’s usual, official and nicknames, practitioners may go by different names at different healthcare services for cultural or other reasons.  Adding a preferred name to the AU Base PractitionerRole profile will allow this to be communicated where required.

The Service Registration Assistant (SRA) Release 1 IG has such an extension.  It is proposed to extend AU Base in a substantially similar manner.
- https://sra.digitalhealth.gov.au/fhir/StructureDefinition-sra-practitioner-role.html
- https://sra.digitalhealth.gov.au/fhir/StructureDefinition-sra-preferred-name.html

**Comment by jdavison-mo** [comment]
Name details are generally in the Practitioner resource, and not PractitionerRole (currently there I don't believe name information in PractitionerRole because it references a Practitioner resource). It is possible to model this with a separate Practitioner resource per practitioner role to address this issue. Systems will know nothing about how to display this extension or process it in a generic way. The Practitioner resource already has the fields that systems know how to process and display, and supports multiple human names allowing for things like "usual" and "nickname". I don't think this specific SRA's internal modelling quirk should be propagated into AU Base. 

Is there a fixation on trying to maintain a single practitioner resource per person? SRA could internally model them as a single practitioner but publish multiple practitioner resources into FHIR to address the modelling mismatch. It will be simple enough for users to recognize that these are all the same practitioner if they want to consider the identifiers of the practitioner e.g. search on identifier would give all practitioners with same identifiers.

Extensions are extensions and can't be relied upon to deliver functionality. In this case use what's already there and it will be reliable.

**Comment by adha-admin** [comment]
Your suggestion Jared around maintaining multiple practitioner resources is the exact reason why there is such a mess when it comes to trying to keep directories clean. If there is one person, there should be only one Practitioner Resource. The PractitionerRole's purpose, therefore, says when they are in this role, call themthis, in the same way, you attach the medicare provider number at the PractitionerRole. Its just a way of identifying them.

**Comment by dtr-agency** [comment]
What is the core FHIR position on why name is not considered appropriate at PractitionerRole? There is a semi-related issue note in 2019 https://jira.hl7.org/browse/FHIR-22112

While I can't see directly adopting this the Clinical Informatics specifications I'm not opposed to its inclusion in AU Base where we can see this should be agreed at the AU Base level and used across multiple implementations.

**Comment by jdavison-mo** [comment]
> Your suggestion Jared around maintaining multiple practitioner resources is the exact reason why there is such a mess when it comes to trying to keep directories clean. If there is one person, there should be only one Practitioner Resource. The PractitionerRole's purpose, therefore, says when they are in this role, call themthis, in the same way, you attach the medicare provider number at the PractitionerRole. Its just a way of identifying them.

I disagree. The directory is a publishing mechanism, it can't be a model of the real world because the FHIR model artefact don't match the real world.

**Comment by robeastwood-agency** [comment]
This was discussed at PAWG today, see [minutes](https://confluence.hl7australia.com/display/PA/2020-08-12+Minutes). 

This was extensively discussed with the outcome that this is more relevant to SRA than HL7 AU. The decision was therefore taken to not introduce this into HL7 AU and to keep this as a SRA extension and review later.

Closing.
