### ISSUE TITLE
AU Base Medication Request - normative defects

### ISSUE THREAD

**Issue by dtr-agency** [hl7au/au-fhir-base#533]
The two identifier slices force failure: it is not possible to satisfy either slice. There is a required binding to a value set, however the fixed code is not a member of that value set - and cardinality constraints allow only one code with one coding.

Required change to identifier:etpVendorIdentifier & identifier:localScriptNumber needs to do one or more of:
* remove the binding
* remove the coding cardinality constraints (too controlled anyway to not allow for translations)
* update to the correct R4 normative code system instead of the legacy STU3 system

**Comment by RichardTON** [comment]
ETP Vendor Identifier profile #524 does not have this problem. The profile has not yet replaced the broken slicing.

**Comment by dtr-agency** [comment]
The profile doesn't yet exist.... so yes it doesn't have this problem :)

**Comment by dbojicic-agency** [comment]
PR with a fix for this issue is forthcoming. 

As agreed with @oridashi, the two identifier will be replaced with [AU ETP Prescription Identifier](file:///C:/work/git/au-fhir-base-r4/output/StructureDefinition-au-etpprescriptionidentifier.html) and [AU Local Prescription Identifier](file:///C:/work/git/au-fhir-base-r4/output/StructureDefinition-au-localprescriptionidentifier.html) data type profiles.

**Comment by dbojicic-agency** [comment]
In internal review with @davidmckillop.

**Comment by davidmckillop** [comment]
Did a build, checked the changes -> no issues found.
added an ETP identifier to medicationrequest-example0.xml -> no qa.html errors as expected;
medicationrequest-example0.xml already had a LPN example -> no qa.html errors as expected;
Added another non-ETP and non-LPN identifier (i.e. NOI) to medicationrequest-example0.xml -> no qa.html errors as expected.
All good.
