### ISSUE TITLE
AU Base Dosage: normative defects

### ISSUE THREAD

**Issue by dtr-agency** [hl7au/au-fhir-base#535]
The additionalInstruction:snomedAdditionalInstruction slice isn't formed properly and isn't functioning - currently throwing an error on any example with an instance of additionalInstruction

**Comment by dbojicic-agency** [comment]
A pull request with fixes for this issue is forthcoming with a few changes, as agree with @oridashi:

- remove additionalInstruction:snomedAdditionalInstruction slice and place terminology binding with the strength of 'preferred' onto the top level element additionalInstruction
- remove asNeeded[x] slices and place the binding on the element; the binding will be ignored when the element is instantiated as asNeededBoolean

**Comment by dbojicic-agency** [comment]
In internal review with @davidmckillop.
