### ISSUE TITLE
Add support for AHPRA Registration Details in AU Base Practitioner

### ISSUE THREAD

**Issue by SatyaYelisetti** [hl7au/au-fhir-base#547]
The proposal is to add a single complex extension to practitioner.qualification to cater for the different elements in an AHPRA registered practitioner. 

The complex extension (ahpraRegistration-details) has extensions in itself for each element of the AHPRA registered profession. A draft of this extension has been attached below for reference. 

AU Base practitioner profile Qualification entry slice ahpraRegistration will not be needed anymore to cater for AHPRA qualification. 

To send a professional qualification registration the qualification.code.text should be used to cover both professional boards and colleges. When it is an AHPRA registered qualification, use the ahpraRegistration-details extension in practitioner.qualification for the AHPRA details and the AUAHPRARegistrationNumber goes in qualification.identifier.

The above proposal will now allow AU Base Practitioner to cater for all professional qualifications, not just AHPRA registered ones. 

A draft of this profile and complex extension can be found here:
http://build.fhir.org/ig/ci-collaborative/au-fhir-base-r4/branches/SRAIG-162-proposal-to-update-ahpra-registration-support-in-au-base-practitioner/
Example here:
http://build.fhir.org/ig/ci-collaborative/au-fhir-base-r4/branches/SRAIG-162-proposal-to-update-ahpra-registration-support-in-au-base-practitioner/Practitioner-example4.html

**Comment by mcguirek** [comment]
### Additional details of proposal
To support the inclusion of AHPRA registration details in the FHIR practitioner resource it is proposed to:
1.	Create a complex extension to contain elements that are currently not supported
2.	Remove the existing ahpraRegistration slice which appears to do little more than to fix the value of issuer.display to “AHPRA” and constrain the identifier to AUAHPRARegistrationNumber.
3.	Include guidance in the usage notes on how to map AHPRA data elements into the resource
4.	Include an example showing this mapping
### Complex extension
The following complex extension is proposed:
http://build.fhir.org/ig/ci-collaborative/au-fhir-base-r4/branches/SRAIG-162-proposal-to-update-ahpra-registration-support-in-au-base-practitioner/StructureDefinition-ahpraregistration-details.html
This includes codeable concepts for a range of AHPRA data elements that are strings from a constrained set of possible values.  These data elements are all candidates for the future creation of defined value sets.  It is not proposed that there is sufficient benefit to create the value sets at this time, since AHPRA data will only contain values defined by AHPRA.  Rather it is proposed to store the values from AHPRA in the codeableconcept.text.  This future-proofs the extension and allows the introduction of defined value sets for these concepts at a later date if required.
The ahpraProfessionStartDate is also proposed for inclusion in the extension as it represents the date of the first registration of this practitioner in this profession, which may be earlier than the start date of this registration (which would be in qualification.period.start).
The ahpraRegistrationRecordNumber is also proposed for inclusion in the extension as a simple string.  It distinguishes between multiple registrations with the same AHPRA profession.
### Remove the existing ahpraRegistration slice
This slice appears to impose unhelpful constraints and is proposed for removal in line with the removal of other slices in AU Base that have been previously agreed.  Removing this slice will allow the consistent representation of registrations with any health professional board, not just AHPRA boards.
An example structure definition with the slice removed and the extension added is here:
http://build.fhir.org/ig/ci-collaborative/au-fhir-base-r4/branches/SRAIG-162-proposal-to-update-ahpra-registration-support-in-au-base-practitioner/StructureDefinition-au-practitioner.html
### Include guidance in the usage notes
It is proposed to include the following mapping guidance in a separate page linked from the usage notes:
A practitioner resource carrying AHPRA data should have a qualification backbone element for each qualification contained in the AHPRA data for the practitioner and a qualification backbone element for each professional board registration contained in the AHPRA data.

AHPRA person data
•	Name Edit Date -> name.period.start
•	Name Title -> name.prefix
•	Family Name -> name.family
•	Given Name -> name.given[1]
•	Middle Name -> name.given[2]

AHPRA qualification data
•	Qualification Title -> qualification.code.text
•	Awarding Institution -> qualification.issuer.resolve().name
•	Country Qualification Obtained -> qualification.issuer.resolve().address.country
•	Year of Qualification -> qualification.period.start

AHPRA registration data
•	Profession Number 
-> identifier:AUAHPRARegistrationNumber AND
-> qualification.identifier:AUAHPRARegistrationNumber
•	Profession -> qualification.code (using above code system)
•	Profession Start Date -> qualification.extension:ahpraprofessionstartdate
•	Registration Record Number -> qualification.extension:ahpraRegistrationRecordNumber
•	Division -> qualification.extension:ahpradivision.text
•	Registration Type -> qualification.extension:ahpraregistrationtype.text
•	Registration Sub-Type -> qualification.extension:ahpraregistrationsubtype.text
•	Registration Status -> qualification.extension:ahpraregistrationstatus.text
•	Registration Expiry -> qualification.period.end
•	Specialty -> qualification.extension:ahpraspecialty.text
•	Field of Specialty Practice -> qualification.extension:ahprafieldofspecialtypractice.text
•	Initial Registration Date -> qualification.period.start
### Include an example using this mapping
The following example is proposed:
http://build.fhir.org/ig/ci-collaborative/au-fhir-base-r4/branches/SRAIG-162-proposal-to-update-ahpra-registration-support-in-au-base-practitioner/Practitioner-example4.json.html

**Comment by mcguirek** [comment]
Proposal as updated on 25 November 2020 (https://github.com/hl7au/au-fhir-base/issues/547#issuecomment-712524518) agreed at PAWG 2 December 2020 (https://confluence.hl7australia.com/display/PA/2020-12-02+Minutes) with proviso that qualification.code binding be preferred rather than extensible.  Also need to add the two new codes to the 0360 table in V2.4 Australian Standard.

**Comment by mcguirek** [comment]
Completed
