### ISSUE TITLE
AllergyIntolerance: Binding to exposureRoute is 'example' 

### ISSUE THREAD

**Issue by vikasmittal-dh** [hl7au/au-fhir-base#572]
The terminology binding to exposureRoute is of type 'example'
http://hl7.org/fhir/allergyintolerance.html
http://hl7.org/fhir/allergyintolerance-definitions.html#AllergyIntolerance.reaction.exposureRoute

The Value Set http://hl7.org/fhir/valueset-route-codes.html is a SNOMED one.
So the query is can we make it preferred using this value set.

An internal Agency ticket with the title "Investigate veracity of core spec valueset for AllergyIntolerance exposureRoute for Australian use" has been logged with the terminology team and the process has been initiated to find if we will need another value set to make it preferred.

**Comment by dtr-agency** [comment]
Terminology assessment:
HL7 defines AllergyIntolerance.reaction.exposureRoute as: Identification of the route by which the subject was exposed to the substance.
(https://www.hl7.org/fhir/allergyintolerance-definitions.html#AllergyIntolerance.reaction.exposureRoute)

And recommends the value set "route-codes", which includes the codes from http://snomed.info/sct  where concept is-a 284009009 (Route of administration values).
(https://www.hl7.org/fhir/valueset-route-codes.html)

284009009|Route of administration values| though sounds like it is limited to routes of medicine administration, all its subtypes essentially describe the routes that a substance can enter or contact the body (171 concepts including self).

After discussions with [~liambarnesamt] and [~mattcordell] (email attached) it was decided that a more constrained value set would be more appropriate, using more general routes.

The following resources describe 4 main routes of exposure to a substance:
1. Inhalation
2. Skin
3. Ingestion
4. Injection
-- (The University of Nebraska's Toxicology and Exposure Guidelines - https://ehs.unl.edu/documents/tox_exposure_guidelines.pdf)
-- (Canadian Centre for Occupational Health and Safety - https://www.ccohs.ca/oshanswers/chemicals/how_chem.html)
-- (Science Direct; Exposure Routes - https://www.sciencedirect.com/topics/earth-and-planetary-sciences/exposure-route)
-- (Science Direct; Allergen - https://www.sciencedirect.com/topics/neuroscience/allergen)

Therefore the value set could be constrained to:
- 447694001 |Respiratory tract route| 
- 447964005 |Digestive tract route| 
- 6064005 |Topical route|

However there is no obvious concept for injection in SNOMED - |424109004 | Injection route| has been inactivated and replaced with |447120003|Injection technique| with reason “Possibly Equivalent".

Science Direct; Allergen (https://www.sciencedirect.com/topics/neuroscience/allergen) describes sources of injected allergens as; hyposensitization injections, intradermal allergen tests, drugs, insect bites, and stings.

The value set could also include the following constraints for injection:
- 372464004 | Intradermal route|
- 78421000 | Intramuscular route|
- 34206005 | Subcutaneous route|
- 445755006 | Intravascular route |

There are more routes of administration (most would be associated with drug administration, rather than allergen exposure - though not mutually exclusive), however at this stage it may be better to constrain this value set as follows:

- 447694001 |Respiratory tract route| 
- 447964005 |Digestive tract route| 
- 6064005 |Topical route|
- 372464004 | Intradermal route|
- 78421000 | Intramuscular route|
- 34206005 | Subcutaneous route|
- 445755006 | Intravascular route|

However some concerns with developing an additional value set to support this.

- The difference between the use of "exposure route" in language/practice and the definition of an anatomical route. I imagine clinicians would refer to things like injection, inhalation and ingestion as routes of exposure but really injection is a technique (and the reason the concept was inactivated in SCT) and the other two are physiological processes. 
- The current binding in FHIR is to routes of administration concepts. Technically these are to define the route by which a substance is administered and not how a substance might inadvertently enter the body. Since the administration of any drug could potentially cause an adverse reaction, all of these concepts would be valid but I'd fear they would be used to describe non-drug reactions. I've noticed that the SNOMED on FHIR group has made a small note of this issue also. https://confluence.ihtsdotools.org/display/FHIR/AllergyIntolerance+Binding

I would prefer we stay silent on this binding at the moment as there is no clear solution on how to represent non-drug substances entering the body in SCT at present while still matching the semantics of the model. There are event concepts that are subtypes of 418307001 |Exposure to biological agent| that include some of this information but are not specific to routes.

The decision has been made to stay silent on this binding at this time. 

*Summary position from terminology*
- The current binding in FHIR is to the SNOMED routes of administration concepts, which define how a substance is administered rather than how an allergen may enter or contact the body.
- We, at this time, do not have a suitable alternative to the current binding in FHIR.

*Response from clinical informatics at the Agency*
Clinical Informatics propose going forwards with the equivalence of 'silence' which is to bind as preferred the Route of Administration value set (https://healthterminologies.gov.au/fhir/ValueSet/route-of-administration-1).

**Comment by dtr-agency** [comment]
Now in progress - PR forthcoming to bind AllergyIntolerance.exposureRoute to (https://healthterminologies.gov.au/fhir/ValueSet/route-of-administration-1 as preferred.

**Comment by davidmckillop** [comment]
Tested the build, checked the output -> all changes as desired.
Tested using an example with a value in the new value set and a value not in the value set i.e. different code system -> no issues found.
No qa.html errors from the change.
All good.
