### ISSUE TITLE
BodyStructure.locationQualifier is bound to a value set with obsolete SCT codes

### ISSUE THREAD

**Issue by RichardTON** [hl7au/au-fhir-base#575]
BodyStructure.locationQualifier uses the core binding to a value set with obsolete SCT codes for left and right. See 
[FHIR-29810](https://jira.hl7.org/browse/FHIR-29810) 
AU BodyStructure should comment about this problem or use its own value set.

**Comment by davidmckillop** [comment]
The issue is the the obsolete codes are present in the HL7 FHIR International Value Set and not in a NCTS defined value set.
The options are:
1) Leave HL7 International to fix the the issue raised in [FHIR-29810](https://jira.hl7.org/browse/FHIR-29810); or
2)  Ask NCTS to create a new value set (I understand there is one in the backlog) and bind the new Value set instead of the HL7 International Value set and when HL7 International fixes their value set remove the link to the NCTS value set.

**Comment by davidmckillop** [comment]
As there are obsolete codes present in the current FHIR core value set (re [FHIR-29810](https://jira.hl7.org/browse/FHIR-29810)) a new value set needs to be developed to resolve this issue.
This newly developed value set may be temporary if/when the HL7 core value set has been republished with the all active codes.
The creation of the new value set will allow for a review to determine if there are any gaps in the current value set content and add content where appropriate.
The new value set will be developed by NCTS and offered to AU Base as preferred binding to AU Base BodyStructure.locationQualifier.

**Comment by dtr-agency** [comment]
In progress fix to bind https://healthterminologies.gov.au/fhir/ValueSet/body-site-relative-site-qualifier-1 to locationQualifier as preferred. Also made a number of correction to wording, style, presentation issues to be consistent with other material in the intro.md and the StructureDefintion.

Corrected the 'sports injury' example to be bone tissue of the left shoulder and introduced use of locationQualifier. Added new example for blister of right foot to ensure an example with morphology.

Updated ignoreWarnings.txt to ignore the warnings on the healthterminologies value set for locationQualifier can't resolve from healthterminologies

**Comment by dtr-agency** [comment]
PR with @robeastwood-agency for review and test.

**Comment by robeastwood-agency** [comment]
Review complete; minor example tweaks needed
