### ISSUE TITLE
HL7 AU examples using different templates

### ISSUE THREAD

**Issue by dbojicic-agency** [hl7au/au-fhir-base#673]
Some examples have a breadcrumb train and a page title in format `"<resource type>/<example id>"`. Example formats inlude XML, JSON and Turtle. 

Others don't have breadcrumbs and the page title is in format `"Example:<resource type>-<example id>"`.
Formats include Narrative, XML, JSON and Turtle. 

For example: 
[List/bdaf4fda-4e98-11e9-8647-d663bd873d93](http://build.fhir.org/ig/hl7au/au-fhir-base/List-e0a6c4a6-4e97-11e9-8647-d663bd873d93.html)
[Example: Practitioner-example0](http://build.fhir.org/ig/hl7au/au-fhir-base/Practitioner-example0.html)

All AU Base examples should be using the same template.

**Comment by robeastwood-agency** [comment]
In the process of reviewing other content (ie a List example), the different template used by the List examples is due to the ig.json not having an entry in the defaults array; ie this is missing:
```json
"List": {
    "template-base": "ex.html",
    "template-format": "ex-format.html"
 }
```
This however does not explain other differences in the rendering of List instances (ie missing blue box for id and profile, element names not in bold).

**Comment by dtr-agency** [comment]
Currently only the narrative form shows up, the raw forms of are all showing the narrative form.

**Comment by dtr-agency** [comment]
Fixed via https://github.com/hl7au/au-fhir-base/commit/31279d0625002833237d2d471e716887bee6dc77
https://github.com/hl7au/au-fhir-base/commit/6fd6a06649b7b24e3d90cb65a74f6e837569b552
