### ISSUE TITLE
HealthcareService.availableTime Timezone

### ISSUE THREAD

**Issue by oridashi** [hl7au/au-fhir-base#68]
look at timezone extension for HealthcareService.availabilityTime

**Comment by robeastwood-agency** [comment]
In the context of the upcoming release 2 of SRA, this is a desired option; but even more broadly, there is likely interest for this in the core spec.

Also note that the same thing applies to [PractitionerRole.availableTime.availableStartTime](http://hl7.org/fhir/R4/practitionerrole-definitions.html#PractitionerRole.availableTime.availableStartTime) and [PractitionerRole.availableTime.availableEndTime](http://hl7.org/fhir/R4/practitionerrole-definitions.html#PractitionerRole.availableTime.availableEndTime)

**Comment by robeastwood-agency** [comment]
I see that there are comments against all of the above respective elements, such that 
> The time zone is expected to be for where this HealthcareService is provided at.

See [HealthcareService.availableTime.availableStartTime](http://hl7.org/fhir/healthcareservice-definitions.html#HealthcareService.availableTime.availableStartTime)

**Comment by brianpos** [comment]
Wondering how this would be applicable where multiple timezones are supported?
Such as a service that runs from 9am Eastern Aus to 5pm Western Aus (essentially spanning all mainland Australian business hours)

**Comment by dtr-agency** [comment]
Telehealth services need this.

**Comment by oridashi** [comment]
See https://build.fhir.nhsd.healthdirect.org.au/StructureDefinition-timezone.html

**Comment by mcguirek** [comment]
Note that whilst “The time zone is expected to be for where this HealthcareService is provided at”, this may not work for all virtual (e.g. telehealth) services that may be available across multiple timezones.  

Some virtual services might state an available time range and make themselves available for that time range within each timezone within its coverage area(s).  In this case, the default rule (The time zone is expected to be for where this HealthcareService is provided at) works for them.  i.e., not matter where you are within the coverage area(s) you can assume the available times apply in your area.

Other virtual services may be available for a time range that is referenced to a single timezone (e.g. the timezone where the provider(s) are based).  In this case, these services should specify the timezone.

Healthcare service available times are defined using the time data type which does not allow inclusion of a timezone.  One reason for this will be that timezones cannot be interpreted without a date (due to daylight savings changes).

The NHSD extension (https://build.fhir.nhsd.healthdirect.org.au/StructureDefinition-timezone.html) allows the timezone to be specified as a string containing the name of a timezone as defined in the IANA Time Zone Database (https://www.iana.org/time-zones).  This is a good solution as it provides a reference into a widely-used reference that allows unambiguous calculations of timezone offsets on any given date.  The NHSD consumer API uses this information to adjust the available times of a healthcare service based on the current date and the location the consumer is querying from.  However, the extension, the value set and the codesystem are all locally defined in the NHSD IG.  AU Base will need to either redefine these or use more widely available definitions.

The FHIR Infrastructure Work Group has defined a core extension for a timezone code (maturity level 1) with a required binding to a valueset (maturity level 0) based on the same IANA Time Zone Database:
https://www.hl7.org/fhir/extension-tz-code.html
https://www.hl7.org/fhir/valueset-timezones.html
The core extension, however, cannot be used with time elements, so is not able to be used for our purposes.  The valueset is potentially able to be used at some point, but has the following problems at present:
•	The maturity is 0
•	The code system URI is https://www.iana.org/time-zones, which is not able to be interpreted by FHIR infrastructure.

Proposed solution:
•	Define an AU Base code system substantially similar to the NHSD code system at http://fhir.nhsd.com.au/CodeSystem/au-timezones
•	Define an AU valueset substantially similar to the NHSD valueset at https://build.fhir.nhsd.healthdirect.org.au/ValueSet-valueset-au-timezone.html
•	Define an extension for use in HealthcareService that draws on content from the NHSD and FHIR core extensions (https://build.fhir.nhsd.healthdirect.org.au/StructureDefinition-timezone.html and https://www.hl7.org/fhir/extension-tz-code.html).  Note that the NHSD extension has a type of string, whereas the core extension has a type of code.  The wiki notes at https://confluence.hl7.org/pages/viewpage.action?pageId=35718826#GuidetoDesigningResources-Whatcodeddatatypeshouldbeused? that “If the data type is 'code', the expansion of the value set bound to is considered to be 'locked' on the date of the release of version of the StructureDefinition with the binding. Subsequent changes to the bound value set or any underlying valuesets or code systems will not be reflected until a new version of the StructureDefinition is published. On the other hand, if the data type is not 'code', it is possible that the expansion of the associated value sets might change over time as the referenced value set and/or any underlying value sets and code systems change.”  Is this why string should be chosen over code?
•	Profile HealthcareService to include the extension in the availableTime and notAvailable BackboneElements.
•	In the future, when an FHIR-compatible international code system is defined based on the IANA Time Zone Database, the AU Base valueset definition can be updated to use it.

**Comment by mcguirek** [comment]
Discussed at PAWG 18/11/2020 https://confluence.hl7australia.com/display/PA/2020-11-18+Minutes
Agreed subject to following changes:

- Extension on time datatype as CodeableConcept  for each of availableStartTime; availableEndTime
- Use https://www.iana.org/time-zones as codesystem as per https://www.hl7.org/fhir/valueset-timezones.html
- Define valueset for Australian timezones - with content as per reference https://build.fhir.nhsd.healthdirect.org.au/ValueSet-valueset-au-timezone.html

**Comment by mcguirek** [comment]
Completed
