### ISSUE TITLE
Body Site Relative Site ValueSet could be more complete with the addition of eye/ENT care concepts

### ISSUE THREAD

**Issue by jaymeemurdoch** [hl7au/au-fhir-base#765]
Ballot issue for 4.1.0: https://jira.hl7australia.com/browse/FHIRIG-219

https://www.healthterminologies.gov.au/integration/R4/fhir/ValueSet/body-site-relative-site-qualifier-1

The Body Site Relative Site Qualifier ValueSet could be improved to support more complex, but common, use cases. For example, eye and ENT care. See the eye care BodyStructure.locationQualifier value set:
https://build.fhir.org/ig/HL7/fhir-eyecare-ig/ValueSet-qualifiers.html.

Reporter:Jaymee Murdoch (on behalf of Agency)
Email:jaymee.murdoch@digitalhealth.gov.au

**Comment by dt-r** [comment]
The AU set exists only because the core FHIR specification had inactive SNOMED concepts - the only difference is changing the inactive concepts to the active concepts. We had intended to this set and use core FHIR when that set had been updated.

Has this query been raised as an addition to the core FHIR specification?

**Comment by brettesler-ext** [comment]
F2F comment : propose to place on hold until specific clinical cases are in scope for WG or TDG

**Comment by hl7auadmin** [comment]
eVote: not a specific proposal; eye care will be discussed re specific use case plans but no existing project

**Comment by brettesler-ext** [comment]
Moved to HL7 Jira [FHIR-46306](https://jira.hl7.org/browse/FHIR-46306)
