### ISSUE TITLE
SNOMED Code in AllergyIntolerance-example1 is inactive and needs to be updated

### ISSUE THREAD

**Issue by mjosborne1** [hl7au/au-fhir-base#814]
The example in https://build.fhir.org/ig/hl7au/au-fhir-base/AllergyIntolerance-example1.html is using an inactive SNOMED code 91930004. The code "91930004|Allergy to eggs|" has been replaced by "213020009|Allergy to egg protein|" in SNOMED CT. Please change the example to use the active replacement concept.

**Comment by dt-r** [comment]
@mjosborne1, agree this change should be made. You can submit a PR if you want to make the fix, otherwise we can pick it up in another maintenance PR.

**Comment by mjosborne1** [comment]
@dt-r I'll fix the example in AU Base and submit a PR but note that it would look different in AU Core as target binding will be a substance not a finding.

**Comment by dt-r** [comment]
@mjosborne1 I agree this issue and PR is just AU Base. 

To my knowledge there is no intentional reuse of same examples in the two IGs so a fix to AU Base example doesn't need to automatically trigger an associated AU Core example change. See https://github.com/hl7au/au-fhir-core to raise issues and/or PR to the current AU Core IG.

**Comment by mjosborne1** [comment]
Pull request created: https://github.com/hl7au/au-fhir-base/pull/817
